// src/constants/const/categories.js

export const CATEGORIES = [
  { id: 1, title: "Cine", icon: "film-outline", color: "#E65100" },
  { id: 2, title: "Club", icon: "people-outline", color: "#5C6BC0" },
  { id: 3, title: "Compras", icon: "bag-outline", color: "#374151" },
  { id: 4, title: "Delivery", icon: "fast-food-outline", color: "#FF6D00" },
  { id: 5, title: "Electrodomésticos", icon: "tv-outline", color: "#795548" },
  {
    id: 6,
    title: "Electrónica",
    icon: "hardware-chip-outline",
    color: "#26A69A",
  },
  { id: 7, title: "Farmacia", icon: "medkit-outline", color: "#EC407A" },
  { id: 8, title: "Formación", icon: "school-outline", color: "#1976D2" },
  { id: 9, title: "Gimnasio", icon: "barbell-outline", color: "#4A148C" },
  { id: 10, title: "Hogar", icon: "home-outline", color: "#8D6E63" },
  { id: 11, title: "Indumentaria", icon: "shirt-outline", color: "#8E24AA" },
  { id: 12, title: "Mascotas", icon: "paw-outline", color: "#D84315" },
  { id: 13, title: "Ocio", icon: "game-controller-outline", color: "#6A1B9A" },
  { id: 14, title: "Regalos", icon: "gift-outline", color: "#FF2E93" },
  {
    id: 15,
    title: "Restaurantes",
    icon: "restaurant-outline",
    color: "#FFB300",
  },
  { id: 16, title: "Salud", icon: "heart-outline", color: "#D32F2F" },
  { id: 17, title: "Servicios", icon: "flash-outline", color: "#00ACC1" },
  { id: 18, title: "Supermercado", icon: "cart-outline", color: "#2E7D32" },
  {
    id: 19,
    title: "Suscripciones",
    icon: "play-circle-outline",
    color: "#00E5FF",
  },
  { id: 20, title: "Teatro", icon: "ticket-outline", color: "#E53935" },
  { id: 21, title: "Tecnología", icon: "laptop-outline", color: "#00B0FF" },
  { id: 22, title: "Transporte", icon: "bus-outline", color: "#546E7A" },
  { id: 23, title: "Vehículo", icon: "car-outline", color: "#263238" },
  { id: 24, title: "Viajes", icon: "airplane-outline", color: "#00838F" },
  { id: 25, title: "Cuidado Personal", icon: "cut-outline", color: "#F06292" },
  {
    id: 26,
    title: "Impuestos y Tasas",
    icon: "document-text-outline",
    color: "#3E2723",
  },
  {
    id: 27,
    title: "Seguros",
    icon: "shield-checkmark-outline",
    color: "#1A237E",
  },
  {
    id: 28,
    title: "Otros",
    icon: "ellipsis-horizontal-circle-outline",
    color: "#9E9E9E",
  },
  { id: 101, title: "Sueldo", icon: "cash-outline", color: "#28cb52" },
  { id: 102, title: "Ventas", icon: "trending-up-outline", color: "#0ea5e9" },
  {
    id: 103,
    title: "Inversiones",
    icon: "stats-chart-outline",
    color: "#8b5cf6",
  },
  {
    id: 104,
    title: "Otros Ingresos",
    icon: "ellipsis-horizontal-circle-outline",
    color: "#6b7280",
  },
];
